ALTER TABLE `Train` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'RETIRED') NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE `ScheduleSeat` MODIFY `status` ENUM('AVAILABLE', 'HELD', 'BOOKED', 'BLOCKED') NOT NULL DEFAULT 'AVAILABLE';
